---
title: "DCM_HVOL_generateData"
author: "risha govind"
date: "13/01/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Data}
DCM_raw <- read.csv("../../data-raw/DCM_pheno_raw.csv", header=T, sep=',')
HVOL_raw <- read.csv("../../data-raw/HVOL_pheno_raw.csv", header=T, sep=',')
postPCA_FinalDataset<- read.table("../input-files/Filtered_SampleIDs.txt", header=T, sep='\t')

dim(DCM_raw)
dim(HVOL_raw)
```

```{r Filtered Data}

### DCM - post filtering
DCM_filtered <- subset(DCM_raw, DCM_raw$Bru.Number %in% postPCA_FinalDataset$IID)


### HVOL - post filtering
HVOL_filtered <- subset(HVOL_raw, HVOL_raw$Bru.Number %in% postPCA_FinalDataset$IID)

dim(DCM_filtered)
dim(HVOL_filtered)

```

```{r Update missing Data}

#update data missing from Paz's pheno file 

DCM_filtered$Ageatscan_years[DCM_filtered$Bru.Number == '10CH00929'] <- 71
DCM_filtered$Ageatscan_years[DCM_filtered$Bru.Number == '10PO01022'] <- 44
DCM_filtered$Ageatscan_years[DCM_filtered$Bru.Number == '10RM00840'] <- 66

```


```{r Drop Columns}

DCM <- DCM_filtered[,c("Ageatscan_years","AgeatBB_years","Race","Sex","Dcm.Eflv","LVEDVI","Dcm.Edvlv","EtOHXS")]
HVOL <- HVOL_filtered[,c("Ageatscan_years","Race","Sex","Hvq.Eflv","Hvq.Edvlv")]

#Add a column : group
DCM<-cbind(group="DCM", DCM)
HVOL<-cbind(group="HVOL", HVOL)

colnames(DCM) <- c("group", "AGE_AT_scan", "AGE_AT_recruitment", "Ethnicity", "SEX", "EF","LVEDVI", "DD","EtOHXS")
colnames(HVOL) <- c("group", "AGE_AT_scan","Ethnicity", "SEX", "EF","DD")

dim(DCM)
dim(HVOL)
```


```{r }

#write table
  write.table(DCM, quote=FALSE, sep ="\t", row.names = F, file="../input-files/DCM_pheno.txt") 
  write.table(HVOL, quote=FALSE, sep ="\t", row.names = F, file="../input-files/HVOL_pheno.txt") 

```

